<?php require('template/header.phtml') ?>

<!-- This is a div that is hidden by default. It is used to display the map. -->
<div class="d-flex justify-content-center pt-2 pb-2" id="mapContainer">
    <!-- This is a div that is hidden by default. It is used to display the map. -->
    <div class="container-xl map border border-2 border-dark shadow-lg " id="map">
    </div>

</div>
<?php require('template/footer.phtml') ?>
