    </div>


    <div class-"row">
        <div id="footer" class="col-xs-12">
            <p>Web-site development using the MVC design pattern and the Bootstrap CSS framework</p>
        </div>
    </div>
<!-- Bootstrap core JavaScript
================================================== -->

    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <!-- map link -->
    <script src="./OpenLayers-2.13.1/OpenLayers.js"></script>
    <!-- map link ends -->


    <script>
    // This is a php code that is used to generate a token.

    var token = '<?php    echo $_SESSION['token']?>';
    var isLoggedIn = '<?php echo isset($_SESSION['user_id'])?>';
    // alert(isLoggedIn);
    var loggedInUser = '<?php if(isset($_SESSION['user_id'])){echo $_SESSION['user_id'];}?>';

    var xml = new XMLHttpRequest();


    // console.log(token);


    </script>
    <script  type="text/javascript" src="./js/map.js"></script>
    <script  type="text/javascript" src="./js/searchUsers.js"></script>

</body>
</html>