<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

    <title>Server-Side Programming - <?php if(isset($view->pageTitle)) {echo $view->pageTitle;} ?></title>
</head>

<body role=""document">

<div class="container">
        <div  class="row">
            <div id="title" class="col-xs-12">
                <img src="images/social-net.png" alt="Salford University" />
                    <div class="pull-right"> <h1><?php echo $view->pageTitle ?> </h1></div>

            </div>
        </div>

    <div class="row">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
        <ul class="nav navbar_default nav-stacked">

        </ul>
            <?php
            if (!isset($_SESSION["login"])) //check for session 'login'
            {
                echo '
                    <form method="post" action="" class="form text-primary">
                        <input id="input-group" type="text" name="username" placeholder="Username...">
                        <input id="input-group" type="password" name="password" placeholder="Password...">
                        <input id="input-group" class="btn btn-default"  type="submit" name="loginBtn" value="Login">
                        <input id="input-group" class="btn btn-default"  type="submit" name="signupBtn" value="Signup">
                    </form>';

                if (isset($_GET['error'])) { //display the login error messages
                    if ($_GET['error'] == "emptyfields") {
                        echo "<p class='error-messages'>Please enter your username & password!</p>";
                    }
                    elseif ($_GET['error'] == "sqlerror") {
                        echo "<p class='error-messages'>There is an issue with server!</p>";
                    }elseif ($_GET['error'] == "usernotfound") {
                        echo "<p class='error-messages'>The username is not found!</p>";
                    }elseif ($_GET['error'] == "wrongpassword") {
                        echo "<p class='error-messages'>The password is wrong!</p>";
                    }
                }
                echo '
                    <li><a id="input-group" href="index.php" class="navbar-toggle">Home</a></li>
                    <li><a id="input-group" href="signup.php" class="navbar-toggle">Signup</a></li>';
                echo '
                <form class="search" method="post" action="./search.php" class="form text-primary">
                   <input id="searchBox" class="form-control" type="text" name="searchBox" placeholder="Search"> 
                 
                </form>
                <div class="drop-d-menu mt-3 shadow-lg w-md-100 ms-md-0" id="drop-d-menu">

                 <!-- This is the div where the search result will be displayed. -->
                    <div class="record-display p-2 w-lg-100 w-xl-100 w-md-100 h-lg-100  justify-content-center" id="record-display">
                     <img class=" shadow-lg rounded-5" id="loading" src="./images/loading.gif"alt="loading" width="15px" height="15px">

    
    
                    </div>


                </div><!--dropdown menu ends here-->

                '; //display search form at the bottom of the menu before login
            } else
            {
                if (isset($_GET['login']) == "successful") { //display a massage after successfully logged in
                    echo '<p class="successful"> '.$_SESSION["login"].' is logged in successfully!</p>';

                }

                //display search form at the top of the menu  after login
                echo '<form method="post" action="" class="form text-primary">

                        <input id="searchBox" class="form-control" type="text" name="searchBox" placeholder="Search...">
                        
                    </form>
                        <!--dropdown menu starts here-->
                        <div class="drop-d-menu mt-3 shadow-lg w-md-100 ms-md-0" id="drop-d-menu">
    
                            <!-- This is the div where the search result will be displayed. -->
                            <div class="record-display p-2 w-lg-100 w-xl-100 w-md-100 h-lg-100  justify-content-center" id="record-display">
                             <img class=" shadow-lg rounded-5" id="loading" src="./images/loading.gif"alt="loading" width="15px" height="15px">
                            </div>
                        </div><!--dropdown menu ends here-->
                    ';

                echo '<form method="post" action="" class="form text-primary">
                        <input id="input-group" class="btn btn-default" type="submit" name="logoutBtn" value="Logout">
                    </form>
                    
                    <li><a id="input-group" href="index.php" class="navbar-toggle">Home</a></li>
                    <li><a id="input-group" href="myProfile.php" class="navbar-toggle">My Profile</a></li>
                    <li><a id="input-group" href="allUsers.php" class="navbar-toggle">Find Friends</a></li>
                    <li><a id="input-group" href="myFriends.php" class="navbar-toggle">My Friends</a></li>
                    <li><a id="input-group" href="map.php" class="navbar-toggle">Map</a></li>';
            }
            ?>

            <?php
            if (isset($_POST['searchWord'])) {
                header('Location: search.php');
            }
                if (isset($_POST["signupBtn"])) {
                    header('Location: signup.php');
                }
            ?>
        </ul>
       </div>

        <!--        token starts here-->
        <?php

        //Generate a random string.
        $token = openssl_random_pseudo_bytes(16);

        //Convert the binary data into hexadecimal representation.
        $token = bin2hex($token);

        /* Setting the session variable `token` to the value of `->token` */
        $_SESSION['token'] = $token;?>
                <!--        token ends here-->


        <div id="content" class="col-xs-6 col-sm-9 col-md-10">



