<?php
require_once './Models/UserData.php';
class UserExtendedData extends UserData implements JsonSerializable {

    protected  $_latitude, $_longitude;

    /**
     * @param $dbRow
     */
    public function __construct($dbRow)
    {
        parent::__construct($dbRow);

        $this->_latitude = $dbRow['latitude'];
        $this->_longitude = $dbRow['longitude'];
    }
    Public function jsonSerialize(){


        return[
            "username"=> $this->username,
            "first_name"=> $this->_firstName,
            "last_name"=> $this->_lastName,
            "email"=>$this->_email,
            "photo_name"=>$this->_photoName,
            "latitude"=> $this->_latitude,
            "longitude"=>$this->_longitude,

        ];
    }

    /**
     * @return mixed
     */
    public function getUsername(): mixed
    {
//        return parent::getUsername(); // TODO: Change the autogenerated stub
        return $this->username;
    }

    /**
     * @return mixed
     */
    public function getLatitude(): mixed
    {
        return $this->_latitude;
    }

    /**
     * @return mixed
     */
    public function getLongitude(): mixed
    {
        return $this->_longitude;
    }


}